# Comments of the type "# DJ packagename (version)" state in which version a dependency
# is contained in Debian Jessie.

name: consumption-env

dependencies:

- python=3.4.2        # DJ python3 (3.4.2-2)
- ruamel_yaml=0.11.14 # DJ has no python3-ruamel.yaml, testing has (0.13.4-2)
- redis-py=2.10.3     # DJ python3-redis (2.10.1-1)
- numpy>=1.8.0        # DJ python3-numpy (1:1.8.2-2)
- pandas>=0.17.1      # DJ python3-pandas (0.14.1-2)
- sqlalchemy=0.9.8    # DJ python3-sqlalchemy (0.9.8+dfsg-0.1)
- psycopg2=2.6.1      # DJ python3-psycopg2 (2.5.4+dfsg-1)

#- ipython=2.3.0      # DJ ipython3 (2.3.0-2)
#- matplotlib          # DJ python3-matplotlib (1.4.2-3.1)

# For nilmtk:

#- pyyaml
#- Cython>=0.19.1
#- bottleneck>=0.6.0
#- numexpr>=2.2.2
#- pytables
#- networkx
#- scipy>=0.16.1
#- scikit-learn>=0.14
#- ipython
#- six
#- future
#- nose
#- coverage
#- pip
#- pip:  # Install packages which are not in conda. Install these using pip:
#    - coveralls
#    - hmmlearn==0.1.1
#   - psycopg2 # not available in conda for Windows.

# Only for development:

#- spyder
